import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

export default function Home() {
  
  const user = useUser();
  const { data, isLoading } = api.sketchbook.getAll.useQuery();

  if (isLoading) return <div>Loading...</div>;

  if (!data) return <div>Something went wrong</div>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-screen">
        <div className="h-full w-full md:max-w-2xl border-x border-slate-400">
          <div className="border-b border-slate-400 p-4">
            {!user.isSignedIn && (
              <div className="flex justify-center">
                <SignInButton />
              </div>
            )}
            {!!user.isSignedIn && <SignOutButton />}
          </div>
          
          <div className="flex flex-col">
            {data?.map((sketchbook) => (
              <div key={sketchbook.id} className="border-b border-slate-400 p-8">
                {sketchbook.title}
                </div>
            ))}
          </div>
        </div>
      </main>
    </>
  );
}
