import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

import { api } from "~/utils/api";
import type { RouterOutputs } from "~/utils/api";

const CreateSketchbook = () => {
  const { user } = useUser();
  
  if (!user) return null;

  return <div className="p-4">
    Create Sketchbook!
  </div>
}

const ProfileBadge = () => {
  const { user } = useUser();
  
  if (!user) return null;

  return <div>
    <Image 
      src={user.imageUrl} 
      alt="Profile" 
      className="w-12 h-12 rounded-full p-4" 
      width={12}
      height={12}
      />
  </div>
}

type SketchbookWithUser = RouterOutputs["sketchbook"]["getById"][number];
const SketchbookView = (sketchbook: SketchbookWithUser ) => {
  return (
    <div key={sketchbook.id} className="border-b border-slate-400 p-8">
                {sketchbook.title}
                </div>
  )
}

export default function Home() {
  
  const user = useUser();
  const userId = user.user?.id ?? null;
  //TODO
  console.log(user);

  if (!userId) return <div>Not logged in</div>;

  const { data, isLoading } = api.sketchbook.getById.useQuery(userId);

  if (isLoading) return <div>Loading...</div>;

  if (!data) return <div>Something went wrong</div>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-screen">
        <div className="h-full w-full md:max-w-2xl border-x border-slate-400">
          <div className="border-b border-slate-400 p-4">
            {!user.isSignedIn && (
              <div className="flex justify-center">
                <SignInButton />
              </div>
            )}
            {!!user.isSignedIn && (
              <div>
              <CreateSketchbook />
              <ProfileBadge />
              </div>
            )}
          </div>
          
          <div className="flex flex-col">
            {data?.map((sketchbook) => (
              <SketchbookView {...sketchbook} key={sketchbook.id} />
            ))}
          </div>
        </div>
      </main>
    </>
  );
}
